name: "Generate plots of professors' lateness"

on: [push]
  # push:
    # paths: 
    #   - "**.ods"

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
        working-directory: misc/lateness
        run: |
          realpath .
          pip install -r requirements.txt
          python lateness.py